import type { Prop } from "./types"

export const DEFAULT_PROPS: Prop[] = [
  {
    id: "p-a1b2c3d4-0001",
    question: "Length of National Anthem (in seconds)",
    optionA: "Over 120",
    optionB: "Under 120",
    correctAnswer: null,
    order: 0,
  },
  {
    id: "p-a1b2c3d4-0002",
    question: "Coin toss result",
    optionA: "Heads",
    optionB: "Tails",
    correctAnswer: null,
    order: 1,
  },
  {
    id: "p-a1b2c3d4-0003",
    question: "Game winner",
    optionA: "Seahawks",
    optionB: "Patriots",
    correctAnswer: null,
    order: 2,
  },
  {
    id: "p-a1b2c3d4-0004",
    question: "Game total",
    optionA: "Over 45.5",
    optionB: "Under 45.5",
    correctAnswer: null,
    order: 3,
  },
  {
    id: "p-a1b2c3d4-0005",
    question: "First offensive play of the game",
    optionA: "Rushing attempt",
    optionB: "Passing attempt",
    correctAnswer: null,
    order: 4,
  },
  {
    id: "p-a1b2c3d4-0006",
    question: "Will there be a scoreless quarter",
    optionA: "Yes",
    optionB: "No",
    correctAnswer: null,
    order: 5,
  },
  {
    id: "p-a1b2c3d4-0007",
    question: "Team to score first",
    optionA: "Seahawks",
    optionB: "Patriots",
    correctAnswer: null,
    order: 6,
  },
  {
    id: "p-a1b2c3d4-0008",
    question: "First team to call a timeout",
    optionA: "Seahawks",
    optionB: "Patriots",
    correctAnswer: null,
    order: 7,
  },
  {
    id: "p-a1b2c3d4-0009",
    question: "First accepted penalty will be against",
    optionA: "Seahawks",
    optionB: "Patriots",
    correctAnswer: null,
    order: 8,
  },
  {
    id: "p-a1b2c3d4-0010",
    question: "Will there be overtime?",
    optionA: "Yes",
    optionB: "No",
    correctAnswer: null,
    order: 9,
  },
  {
    id: "p-a1b2c3d4-0011",
    question: "Will a team score 3 consecutive times (not incl PATs)",
    optionA: "Yes",
    optionB: "No",
    correctAnswer: null,
    order: 10,
  },
  {
    id: "p-a1b2c3d4-0012",
    question: "Sam Darnold passing yards",
    optionA: "Over 230.5",
    optionB: "Under 230.5",
    correctAnswer: null,
    order: 11,
  },
  {
    id: "p-a1b2c3d4-0013",
    question: "Drake Maye passing yards",
    optionA: "Over 220.5",
    optionB: "Under 220.5",
    correctAnswer: null,
    order: 12,
  },
  {
    id: "p-a1b2c3d4-0014",
    question: "Total receiving yards - Jaxon Smith-Njigba",
    optionA: "Over 93.5",
    optionB: "Under 93.5",
    correctAnswer: null,
    order: 13,
  },
  {
    id: "p-a1b2c3d4-0015",
    question: "Total receiving yards - Stephon Diggs",
    optionA: "Over 43.5",
    optionB: "Under 43.5",
    correctAnswer: null,
    order: 14,
  },
  {
    id: "p-a1b2c3d4-0016",
    question: "Total rushing yards - Kenneth Walker III",
    optionA: "Over 42.5",
    optionB: "Under 42.5",
    correctAnswer: null,
    order: 15,
  },
  {
    id: "p-a1b2c3d4-0017",
    question: "Team with the longest successful field goal",
    optionA: "Seahawks",
    optionB: "Patriots",
    correctAnswer: null,
    order: 16,
  },
  {
    id: "p-a1b2c3d4-0018",
    question: "Length of longest touchdown (in yards)",
    optionA: "Over 36.5",
    optionB: "Under 36.5",
    correctAnswer: null,
    order: 17,
  },
  {
    id: "p-a1b2c3d4-0019",
    question: "Team with longest touchdown",
    optionA: "Seahawks",
    optionB: "Patriots",
    correctAnswer: null,
    order: 18,
  },
  {
    id: "p-a1b2c3d4-0020",
    question: "Total game score",
    optionA: "Odd",
    optionB: "Even",
    correctAnswer: null,
    order: 19,
  },
  {
    id: "p-a1b2c3d4-0021",
    question: "Highest scoring half",
    optionA: "First",
    optionB: "Second",
    correctAnswer: null,
    order: 20,
  },
  {
    id: "p-a1b2c3d4-0022",
    question: "Total number of touchdowns in the game",
    optionA: "Over 5.5",
    optionB: "Under 5.5",
    correctAnswer: null,
    order: 21,
  },
  {
    id: "p-a1b2c3d4-0023",
    question: "Will there be a missed PAT (1 or 2 pt attempt)",
    optionA: "Yes",
    optionB: "No",
    correctAnswer: null,
    order: 22,
  },
  {
    id: "p-a1b2c3d4-0024",
    question: "Color of Gatorade bath",
    optionA: "Orange/Water/Clear",
    optionB: "Any other color",
    correctAnswer: null,
    order: 23,
  },
  {
    id: "p-a1b2c3d4-0025",
    question: "Position of Superbowl MVP",
    optionA: "Quarterback",
    optionB: "Any other position",
    correctAnswer: null,
    order: 24,
  },
]
